### ISSUE TITLE
 implement customer transform plugin

### ISSUE THREAD

**Issue by hujiayu** [AndreDCMartins/sklearn2pmml-plugin-ensemblePOC#1]
I have little experience in Java . Would you please help me to write the java plugin of my feature transformer. Below is my feature transformer.

#class FeatureSelector(BaseEstimator, TransformerMixin):
class FeatureSelector(TransformerMixin):
    '''A transformer for extracting certain column(s)'''
    def __init__(self, cols):
        self.cols = cols

    def fit(self, X, y=None, **fit_params):
        return self

    def transform(self, X, **transform_params):
        return X[self.cols]

class ModelTransformer(TransformerMixin):

    def __init__(self, model):
        self.model = model

    def fit(self, *args, **kwargs):
        self.model.fit(*args, **kwargs)
        return self

    def transform(self, X, **transform_params):
        return pd.DataFrame(self.model.predict(X))

**Comment by AndreDCMartins** [comment]
For the selection of features you can use the DataFrameMapper object to achieve the same thing. 
No need for a new transformer.

For the ModelTransformer I don't know the purpose of this, if the goal is to use the predictions of a model in a middle step inside a pipeline you can use FeatureUnion with VotingClassifier wrapping up a model object.

If you think they are still of some value, I would add open an issue in https://github.com/jpmml/sklearn2pmml, this way they would be implemented with a more general purpose
